apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: bakcend
    component: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: bakcend
      component: cart
  template:
    metadata:
      labels:
        project: roboshop
        tier: bakcend
        component: cart
    spec:
      containers:  
      - name: cart
        image: talarisureshdevops/cart:2.0.0
        imagePullPolicy: Always
        resources:
          request:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
spec:
  selector:
     project: roboshop
     tier: bakcend
     component: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
