apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels: 
    project: roboshop
    tier: bakcend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: catalogue
  namespace: roboshop
  labels: 
    project: roboshop
    tier: bakcend
    component: catalogue
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      tier: bakcend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        tier: bakcend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: talarisureshdevops/catalogue:2.0.0
        imagePullPolicy: Always # safe to pull everytime, there may be images with same version rebuilt and pushed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: bakcend
    component: catalogue
spec:
  selector:
    project: roboshop
    tier: bakcend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080 #service port
    targetPort: 8080
